### ISSUE TITLE
I constantly have the same issue:

### ISSUE THREAD

**Issue by mozbeel** [silbinarywolf/sdl-zig-demo-emscripten#3]
[leeb@matthias-desktop:~/Projects/sdl-zig-demo-emscripten]$ zig build run
/home/leeb/Projects/sdl-zig-demo-emscripten/build.zig:282:42: error: no field or member function named 'iterateDependencies' in 'Build.Module'
    var it = options.lib_main.root_module.iterateDependencies(options.lib_main, false);
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
/nix/store/55609r49jmh9kzdbcxclx2f5cq9ifk31-zig-0.14.1/lib/zig/std/Build/Module.zig:1:1: note: struct declared here
/// The one responsible for creating this module.
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/leeb/Projects/sdl-zig-demo-emscripten/build.zig:282:42: note: method invocation only supports up to one level of implicit pointer dereferencing
/home/leeb/Projects/sdl-zig-demo-emscripten/build.zig:282:42: note: use '.*' to dereference pointer
referenced by:
    build: /home/leeb/Projects/sdl-zig-demo-emscripten/build.zig:66:41
    runBuild__anon_24680: /nix/store/55609r49jmh9kzdbcxclx2f5cq9ifk31-zig-0.14.1/lib/zig/std/Build.zig:2428:44
    6 reference(s) hidden; use '-freference-trace=8' to see all references
/home/leeb/Projects/sdl-zig-demo-emscripten/deps/sdl/build.zig:16:8: error: no field or member function named 'defineCMacro' in 'Build.Step.Compile'
    lib.defineCMacro("SDL_USE_BUILTIN_OPENGL_DEFINITIONS", "1");
    ~~~^~~~~~~~~~~~~
/nix/store/55609r49jmh9kzdbcxclx2f5cq9ifk31-zig-0.14.1/lib/zig/std/Build/Step/Compile.zig:1:1: note: struct declared here
const builtin = @import("builtin");
^~~~~
/home/leeb/Projects/sdl-zig-demo-emscripten/deps/sdl/build.zig:16:8: note: method invocation only supports up to one level of implicit pointer dereferencing
/home/leeb/Projects/sdl-zig-demo-emscripten/deps/sdl/build.zig:16:8: note: use '.*' to dereference pointer


And I tried everything but can't get it to work with Zig version 0.14.1. And this is literally the original repository.
